language: go
go:
  1.8

install:
  - go get github.com/mattn/goveralls
  - go get

script:
  - go test -coverprofile=fibgo.coverprofile
  - goveralls -coverprofile=fibgo.coverprofile -service=travis-ci
