language: go
go:
  1.8

before_install:
  - go get github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - go get ./... -d -t

before_script:
  - go test -coverprofile=fibgo.coverprofile
  - gometalinter --deadline=15s

script:
  - go install

after_success:
  - goveralls -coverprofile=fibgo.coverprofile -service=travis-ci
